PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX hralit: <https://purl.humanatlas.io/g/hra-lit/v0.1#>
PREFIX role: <http://schema.org/roleName>

SELECT ?source_role ?type_iri ?target_role (COUNT(*) as ?weight)
FROM <https://purl.humanatlas.io/g/hra-lit/v0.1>
WHERE {
  ?source_iri role: ?source_role .
  ?target_iri role: ?target_role .

  ?source_iri ?type_iri ?target_iri .
}
GROUP BY ?source_role ?type_iri ?target_role
