PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX hralit: <https://purl.humanatlas.io/g/hra-lit/v0.1#>
PREFIX role: <http://schema.org/roleName>

SELECT DISTINCT ?iri ?role ?label
FROM <https://purl.humanatlas.io/g/hra-lit/v0.1>
WHERE {
  ?iri role: ?role .
  ?iri rdfs:label ?label .
}
