PREFIX dbxref: <http://www.geneontology.org/formats/oboInOwl#hasDbXref>
PREFIX ccf: <http://purl.org/ccf/>
PREFIX has_characterizing_biomarker_set: <http://purl.obolibrary.org/obo/RO_0015004>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sp: <https://semopenalex.org/property/>

CONSTRUCT {
  ?term dbxref: ?xref
}
FROM <https://purl.org/ccf/releases/2.2.1/ccf.owl>
WHERE {
  {
    ?ref_organ ccf:has_reference_organ ?ref_organ .
    ?ref_organ ccf:representation_of ?term .
  }
  UNION {
    ?term ccf:ccf_asctb_type ?asctb_type .
  }
  UNION {
    # Find biomarkers that characterize the cell type
    ?ct rdfs:subClassOf [
      owl:onProperty has_characterizing_biomarker_set: ;
      owl:someValuesFrom [ owl:intersectionOf ?bn3 ]] .
    ?bn3 rdf:rest*/rdf:first [
      owl:onProperty ccf:has_marker_component ;
      owl:someValuesFrom ?_biomarker_iri ;
      owl:someValuesFrom ?term
    ] .
  }

  {
    SERVICE <https://ubergraph.apps.renci.org/sparql> {
      ?term dbxref: ?xref .
      FILTER (STRSTARTS(?xref, 'Wikipedia:') || STRSTARTS(?xref, 'UMLS:'))
    }
  }
}
