PREFIX dbxref: <http://www.geneontology.org/formats/oboInOwl#hasDbXref>
PREFIX ccf: <http://purl.org/ccf/>
PREFIX has_characterizing_biomarker_set: <http://purl.obolibrary.org/obo/RO_0015004>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sp: <https://semopenalex.org/property/>

CONSTRUCT {
  ?concept dbxref: ?xrefStr .
}
WHERE
{
  {
    ?concept sp:umlsCui ?cui .
    BIND(CONCAT('UMLS:', ?cui) as ?xrefStr)
  }
  UNION
  {
    ?concept rdfs:seeAlso ?otherConcept .
    BIND(REPLACE(STR(?otherConcept), 'https://en.wikipedia.org/wiki/', 'Wikipedia:') as ?xrefStr)
  }

  FILTER (STRSTARTS(?xrefStr, 'Wikipedia:') || STRSTARTS(?xrefStr, 'UMLS:'))
}
