PREFIX dbxref: <http://www.geneontology.org/formats/oboInOwl#hasDbXref>
PREFIX ccf: <http://purl.org/ccf/>

CONSTRUCT {
  ?concept ccf:ccf_term ?term .
}
WHERE {
  ?term dbxref: ?xref .
  ?concept dbxref: ?xref .

  FILTER(STRSTARTS(STR(?concept), 'https://semopenalex.org/concept/'))
  FILTER(!STRSTARTS(STR(?term), 'https://semopenalex.org/concept/'))
}
