PREFIX ccf: <http://purl.org/ccf/>
PREFIX sp: <https://semopenalex.org/property/>
PREFIX fabio: <http://purl.org/spar/fabio/>

SELECT (COUNT(DISTINCT ?publication) as ?cnt)
WHERE {
  VALUES (?concept) {
    ( <https://semopenalex.org/concept/C15336307> ) 
    ( <https://semopenalex.org/concept/C2993163795> ) 
    ( <https://semopenalex.org/concept/C2776280935> ) 
    ( <https://semopenalex.org/concept/C2778292851> ) 
    ( <https://semopenalex.org/concept/C2776364125> ) 
    ( <https://semopenalex.org/concept/C2780601773> ) 
    ( <https://semopenalex.org/concept/C2781041448> ) 
    ( <https://semopenalex.org/concept/C2777348757> ) 
    ( <https://semopenalex.org/concept/C5512455> ) 
    ( <https://semopenalex.org/concept/C2777714996> ) 
    ( <https://semopenalex.org/concept/C3018587741> ) 
    ( <https://semopenalex.org/concept/C2909538045> ) 
    ( <https://semopenalex.org/concept/C2779744229> ) 
    ( <https://semopenalex.org/concept/C2993337849> ) 
    ( <https://semopenalex.org/concept/C2778373776> ) 
    ( <https://semopenalex.org/concept/C2992241549> ) 
    ( <https://semopenalex.org/concept/C2779329155> ) 
    ( <https://semopenalex.org/concept/C137711082> ) 
    ( <https://semopenalex.org/concept/C2779973185> ) 
    ( <https://semopenalex.org/concept/C2910542373> ) 
    ( <https://semopenalex.org/concept/C2776809568> ) 
    ( <https://semopenalex.org/concept/C2908992689> ) 
    ( <https://semopenalex.org/concept/C2777882243> ) 
    ( <https://semopenalex.org/concept/C2775885956> ) 
    ( <https://semopenalex.org/concept/C2776992346> ) 
    ( <https://semopenalex.org/concept/C2779980429> ) 
    ( <https://semopenalex.org/concept/C2776444015> ) 
    ( <https://semopenalex.org/concept/C2776248900> ) 
    ( <https://semopenalex.org/concept/C2777216303> ) 
    ( <https://semopenalex.org/concept/C2777300098> ) 
    ( <https://semopenalex.org/concept/C2777363609> ) 
    ( <https://semopenalex.org/concept/C2777624698> ) 
    ( <https://semopenalex.org/concept/C2778934254> ) 
    ( <https://semopenalex.org/concept/C130327135> ) 
    ( <https://semopenalex.org/concept/C3019965523> ) 
    ( <https://semopenalex.org/concept/C2781085983> ) 
    ( <https://semopenalex.org/concept/C2910760841> ) 
    ( <https://semopenalex.org/concept/C2778001805> ) 
    ( <https://semopenalex.org/concept/C2780091579> ) 
    ( <https://semopenalex.org/concept/C3020395395> ) 
    ( <https://semopenalex.org/concept/C2776235491> ) 
    ( <https://semopenalex.org/concept/C2993530982> ) 
    ( <https://semopenalex.org/concept/C2994223898> ) 
    ( <https://semopenalex.org/concept/C2911054351> ) 
    ( <https://semopenalex.org/concept/C2911124710> ) 
    ( <https://semopenalex.org/concept/C3017587882> ) 
    ( <https://semopenalex.org/concept/C171089720> ) 
    ( <https://semopenalex.org/concept/C2776953305> ) 
    ( <https://semopenalex.org/concept/C3018059006> ) 
    ( <https://semopenalex.org/concept/C2909980255> ) 
    ( <https://semopenalex.org/concept/C2777495146> ) 
    ( <https://semopenalex.org/concept/C534529494> ) 
    ( <https://semopenalex.org/concept/C2779644171> ) 
    ( <https://semopenalex.org/concept/C2781231759> ) 
    ( <https://semopenalex.org/concept/C2909587778> ) 
    ( <https://semopenalex.org/concept/C3018884230> ) 
    ( <https://semopenalex.org/concept/C2777129507> ) 
    ( <https://semopenalex.org/concept/C2775883341> ) 
    ( <https://semopenalex.org/concept/C2780474809> ) 
    ( <https://semopenalex.org/concept/C2909717120> ) 
    ( <https://semopenalex.org/concept/C2777226302> ) 
    ( <https://semopenalex.org/concept/C2777378192> ) 
    ( <https://semopenalex.org/concept/C2910873529> ) 
    ( <https://semopenalex.org/concept/C2780940725> ) 
    ( <https://semopenalex.org/concept/C2781012678> ) 
    ( <https://semopenalex.org/concept/C2993931576> ) 
    ( <https://semopenalex.org/concept/C205383261> ) 
    ( <https://semopenalex.org/concept/C2780849966> ) 
    ( <https://semopenalex.org/concept/C2776366702> ) 
    ( <https://semopenalex.org/concept/C2777740455> ) 
    ( <https://semopenalex.org/concept/C2992879611> ) 
    ( <https://semopenalex.org/concept/C2777479560> ) 
    ( <https://semopenalex.org/concept/C2993138411> ) 
    ( <https://semopenalex.org/concept/C2777093970> ) 
    ( <https://semopenalex.org/concept/C2909292024> ) 
    ( <https://semopenalex.org/concept/C2910227669> ) 
    ( <https://semopenalex.org/concept/C2776116199> ) 
    ( <https://semopenalex.org/concept/C2776445023> ) 
    ( <https://semopenalex.org/concept/C2780552095> ) 
    ( <https://semopenalex.org/concept/C2780788075> ) 
    ( <https://semopenalex.org/concept/C2780775167> ) 
    ( <https://semopenalex.org/concept/C2776206872> ) 
    ( <https://semopenalex.org/concept/C3018637420> ) 
    ( <https://semopenalex.org/concept/C3017506456> ) 
    ( <https://semopenalex.org/concept/C2778324911> ) 
    ( <https://semopenalex.org/concept/C3020135677> ) 
    ( <https://semopenalex.org/concept/C2778801244> ) 
    ( <https://semopenalex.org/concept/C2779066055> ) 
    ( <https://semopenalex.org/concept/C2776391266> ) 
    ( <https://semopenalex.org/concept/C2909677699> ) 
    ( <https://semopenalex.org/concept/C2777236700> ) 
    ( <https://semopenalex.org/concept/C3018845634> ) 
    ( <https://semopenalex.org/concept/C2780554211> ) 
    ( <https://semopenalex.org/concept/C3020292418> ) 
    ( <https://semopenalex.org/concept/C2779835254> ) 
    ( <https://semopenalex.org/concept/C3017433307> ) 
    ( <https://semopenalex.org/concept/C2780913275> ) 
    ( <https://semopenalex.org/concept/C47089857> ) 
    ( <https://semopenalex.org/concept/C2780368125> ) 
    ( <https://semopenalex.org/concept/C120228162> ) 
    ( <https://semopenalex.org/concept/C2778110749> ) 
    ( <https://semopenalex.org/concept/C2777939775> ) 
    ( <https://semopenalex.org/concept/C2778987478> ) 
    ( <https://semopenalex.org/concept/C2779570255> ) 
    ( <https://semopenalex.org/concept/C2776634560> ) 
    ( <https://semopenalex.org/concept/C2780520971> ) 
    ( <https://semopenalex.org/concept/C2781046184> ) 
    ( <https://semopenalex.org/concept/C2780798337> ) 
    ( <https://semopenalex.org/concept/C2776889875> ) 
    ( <https://semopenalex.org/concept/C2778931672> ) 
    ( <https://semopenalex.org/concept/C2776586934> ) 
    ( <https://semopenalex.org/concept/C2779110535> ) 
    ( <https://semopenalex.org/concept/C2777397368> ) 
    ( <https://semopenalex.org/concept/C2778811784> ) 
    ( <https://semopenalex.org/concept/C2779652256> ) 
    ( <https://semopenalex.org/concept/C2992333117> ) 
    ( <https://semopenalex.org/concept/C2780680797> ) 
    ( <https://semopenalex.org/concept/C2910067010> ) 
    ( <https://semopenalex.org/concept/C2781416072> ) 
    ( <https://semopenalex.org/concept/C2994264995> ) 
    ( <https://semopenalex.org/concept/C2909253048> ) 
    ( <https://semopenalex.org/concept/C2780405337> ) 
    ( <https://semopenalex.org/concept/C2776318020> ) 
    ( <https://semopenalex.org/concept/C2781012200> ) 
    ( <https://semopenalex.org/concept/C2781138976> ) 
    ( <https://semopenalex.org/concept/C2779946567> ) 
    ( <https://semopenalex.org/concept/C2781099131> ) 
    ( <https://semopenalex.org/concept/C2993858690> ) 
    ( <https://semopenalex.org/concept/C2779033008> ) 
    ( <https://semopenalex.org/concept/C2910727132> ) 
    ( <https://semopenalex.org/concept/C2908767450> ) 
    ( <https://semopenalex.org/concept/C2908794349> ) 
    ( <https://semopenalex.org/concept/C2776882836> ) 
    ( <https://semopenalex.org/concept/C2909399601> ) 
    ( <https://semopenalex.org/concept/C3017636755> ) 
    ( <https://semopenalex.org/concept/C2909028682> ) 
    ( <https://semopenalex.org/concept/C2781151446> ) 
    ( <https://semopenalex.org/concept/C2776664737> ) 
    ( <https://semopenalex.org/concept/C2779863012> ) 
    ( <https://semopenalex.org/concept/C2781074409> ) 
    ( <https://semopenalex.org/concept/C2910798071> ) 
    ( <https://semopenalex.org/concept/C3019193636> ) 
    ( <https://semopenalex.org/concept/C2909437798> ) 
    ( <https://semopenalex.org/concept/C2909587778> ) 
    ( <https://semopenalex.org/concept/C3018884230> ) 
    ( <https://semopenalex.org/concept/C2779742232> ) 
    ( <https://semopenalex.org/concept/C2908736133> ) 
    ( <https://semopenalex.org/concept/C3020573985> ) 
    ( <https://semopenalex.org/concept/C3018143345> ) 
    ( <https://semopenalex.org/concept/C3019391314> ) 
    ( <https://semopenalex.org/concept/C2909736353> ) 
    ( <https://semopenalex.org/concept/C2778764654> ) 
    ( <https://semopenalex.org/concept/C2994426959> ) 
    ( <https://semopenalex.org/concept/C2776659949> ) 
    ( <https://semopenalex.org/concept/C3020436252> ) 
    ( <https://semopenalex.org/concept/C2910269628> ) 
    ( <https://semopenalex.org/concept/C2910396648> ) 
    ( <https://semopenalex.org/concept/C2777652487> ) 
    ( <https://semopenalex.org/concept/C2910672364> ) 
    ( <https://semopenalex.org/concept/C2777543888> ) 
    ( <https://semopenalex.org/concept/C2780714102> ) 
    ( <https://semopenalex.org/concept/C2780007613> ) 
    ( <https://semopenalex.org/concept/C2910856063> ) 
    ( <https://semopenalex.org/concept/C3018920779> ) 
    ( <https://semopenalex.org/concept/C2778305430> ) 
    ( <https://semopenalex.org/concept/C2911061479> ) 
    ( <https://semopenalex.org/concept/C2911171335> ) 
    ( <https://semopenalex.org/concept/C2911204043> ) 
    ( <https://semopenalex.org/concept/C2910216633> ) 
    ( <https://semopenalex.org/concept/C2983163835> ) 
    ( <https://semopenalex.org/concept/C2777127467> ) 
    ( <https://semopenalex.org/concept/C2991944018> ) 
    ( <https://semopenalex.org/concept/C2780766565> ) 
    ( <https://semopenalex.org/concept/C2778434673> ) 
    ( <https://semopenalex.org/concept/C2992610612> ) 
    ( <https://semopenalex.org/concept/C2776229121> ) 
    ( <https://semopenalex.org/concept/C2993177591> ) 
    ( <https://semopenalex.org/concept/C2777003273> ) 
    ( <https://semopenalex.org/concept/C2908656328> ) 
    ( <https://semopenalex.org/concept/C2993719464> ) 
    ( <https://semopenalex.org/concept/C81388566> ) 
    ( <https://semopenalex.org/concept/C2776870353> ) 
    ( <https://semopenalex.org/concept/C2777075493> ) 
    ( <https://semopenalex.org/concept/C2778897929> ) 
    ( <https://semopenalex.org/concept/C2779715522> ) 
    ( <https://semopenalex.org/concept/C203527163> ) 
    ( <https://semopenalex.org/concept/C53009064> ) 
    ( <https://semopenalex.org/concept/C2780059843> ) 
    ( <https://semopenalex.org/concept/C2780472225> ) 
    ( <https://semopenalex.org/concept/C2778046553> ) 
    ( <https://semopenalex.org/concept/C2778180168> ) 
    ( <https://semopenalex.org/concept/C2775893721> ) 
    ( <https://semopenalex.org/concept/C2775872116> ) 
    ( <https://semopenalex.org/concept/C2777303625> ) 
    ( <https://semopenalex.org/concept/C2777522714> ) 
    ( <https://semopenalex.org/concept/C2778854125> ) 
    ( <https://semopenalex.org/concept/C2779480337> ) 
    ( <https://semopenalex.org/concept/C2910595225> ) 
    ( <https://semopenalex.org/concept/C2780776380> ) 
    ( <https://semopenalex.org/concept/C2775901793> ) 
    ( <https://semopenalex.org/concept/C2777100477> ) 
    ( <https://semopenalex.org/concept/C2779257441> ) 
    ( <https://semopenalex.org/concept/C2780345532> ) 
    ( <https://semopenalex.org/concept/C2778517091> ) 
    ( <https://semopenalex.org/concept/C2776984510> ) 
    ( <https://semopenalex.org/concept/C2778620301> ) 
    ( <https://semopenalex.org/concept/C178635117> ) 
    ( <https://semopenalex.org/concept/C2779777117> ) 
    ( <https://semopenalex.org/concept/C2776694393> ) 
    ( <https://semopenalex.org/concept/C2778434524> ) 
    ( <https://semopenalex.org/concept/C2777695862> ) 
    ( <https://semopenalex.org/concept/C2779021416> ) 
    ( <https://semopenalex.org/concept/C2780646683> ) 
    ( <https://semopenalex.org/concept/C2780931953> ) 
    ( <https://semopenalex.org/concept/C198004926> ) 
    ( <https://semopenalex.org/concept/C126125632> ) 
    ( <https://semopenalex.org/concept/C2776619665> ) 
    ( <https://semopenalex.org/concept/C122129578> ) 
    ( <https://semopenalex.org/concept/C2778048536> ) 
    ( <https://semopenalex.org/concept/C2778677889> ) 
    ( <https://semopenalex.org/concept/C2781069035> ) 
    ( <https://semopenalex.org/concept/C2777670902> ) 
    ( <https://semopenalex.org/concept/C2993059035> ) 
    ( <https://semopenalex.org/concept/C3018390542> ) 
    ( <https://semopenalex.org/concept/C3020766347> ) 
    ( <https://semopenalex.org/concept/C2776382857> ) 
    ( <https://semopenalex.org/concept/C3020332539> ) 
    ( <https://semopenalex.org/concept/C2775984611> ) 
    ( <https://semopenalex.org/concept/C2910234982> ) 
    ( <https://semopenalex.org/concept/C2776793567> ) 
    ( <https://semopenalex.org/concept/C2777470907> ) 
    ( <https://semopenalex.org/concept/C2780496858> ) 
    ( <https://semopenalex.org/concept/C2776886281> ) 
    ( <https://semopenalex.org/concept/C2778034410> ) 
    ( <https://semopenalex.org/concept/C2780382662> ) 
    ( <https://semopenalex.org/concept/C2780382662> ) 
    ( <https://semopenalex.org/concept/C2778394091> ) 
    ( <https://semopenalex.org/concept/C2775841333> ) 
    ( <https://semopenalex.org/concept/C2776674566> ) 
    ( <https://semopenalex.org/concept/C2777031167> ) 
    ( <https://semopenalex.org/concept/C2778200203> ) 
    ( <https://semopenalex.org/concept/C2778333808> ) 
    ( <https://semopenalex.org/concept/C2780540156> ) 
    ( <https://semopenalex.org/concept/C2781072225> ) 
    ( <https://semopenalex.org/concept/C552161191> ) 
    ( <https://semopenalex.org/concept/C2779480072> ) 
    ( <https://semopenalex.org/concept/C104996578> ) 
    ( <https://semopenalex.org/concept/C2780539906> ) 
    ( <https://semopenalex.org/concept/C2781441883> ) 
    ( <https://semopenalex.org/concept/C2779762690> ) 
    ( <https://semopenalex.org/concept/C2780193326> ) 
    ( <https://semopenalex.org/concept/C2778187257> ) 
    ( <https://semopenalex.org/concept/C2778249958> ) 
    ( <https://semopenalex.org/concept/C2780977465> ) 
    ( <https://semopenalex.org/concept/C2780965494> ) 
    ( <https://semopenalex.org/concept/C2778088351> ) 
    ( <https://semopenalex.org/concept/C2780689522> ) 
    ( <https://semopenalex.org/concept/C2777411675> ) 
    ( <https://semopenalex.org/concept/C2776608385> ) 
    ( <https://semopenalex.org/concept/C2781223406> ) 
    ( <https://semopenalex.org/concept/C2993827019> ) 
    ( <https://semopenalex.org/concept/C2781427539> ) 
    ( <https://semopenalex.org/concept/C2775845063> ) 
    ( <https://semopenalex.org/concept/C2775856269> ) 
    ( <https://semopenalex.org/concept/C2779670087> ) 
    ( <https://semopenalex.org/concept/C2781064879> ) 
    ( <https://semopenalex.org/concept/C2781404750> ) 
    ( <https://semopenalex.org/concept/C2992333117> ) 
    ( <https://semopenalex.org/concept/C2780999072> ) 
    ( <https://semopenalex.org/concept/C2776955114> ) 
    ( <https://semopenalex.org/concept/C106207104> ) 
    ( <https://semopenalex.org/concept/C2779921676> ) 
    ( <https://semopenalex.org/concept/C2776024998> ) 
    ( <https://semopenalex.org/concept/C2778542873> ) 
    ( <https://semopenalex.org/concept/C2779048510> ) 
    ( <https://semopenalex.org/concept/C2780744974> ) 
    ( <https://semopenalex.org/concept/C2781171461> ) 
    ( <https://semopenalex.org/concept/C2780880470> ) 
    ( <https://semopenalex.org/concept/C2781149210> ) 
    ( <https://semopenalex.org/concept/C2776021025> ) 
    ( <https://semopenalex.org/concept/C2779365249> ) 
    ( <https://semopenalex.org/concept/C2777679800> ) 
    ( <https://semopenalex.org/concept/C2779684181> ) 
    ( <https://semopenalex.org/concept/C2780138493> ) 
    ( <https://semopenalex.org/concept/C2777892620> ) 
    ( <https://semopenalex.org/concept/C2779570749> ) 
    ( <https://semopenalex.org/concept/C2776104385> ) 
    ( <https://semopenalex.org/concept/C2777957205> ) 
    ( <https://semopenalex.org/concept/C2776725920> ) 
    ( <https://semopenalex.org/concept/C2778453392> ) 
    ( <https://semopenalex.org/concept/C2779714868> ) 
    ( <https://semopenalex.org/concept/C2780413690> ) 
    ( <https://semopenalex.org/concept/C2781078443> ) 
    ( <https://semopenalex.org/concept/C2781328162> ) 
    ( <https://semopenalex.org/concept/C2780680797> ) 
    ( <https://semopenalex.org/concept/C2779922919> ) 
    ( <https://semopenalex.org/concept/C2778402387> ) 
    ( <https://semopenalex.org/concept/C2908732032> ) 
    ( <https://semopenalex.org/concept/C2775926640> ) 
    ( <https://semopenalex.org/concept/C2910707947> ) 
    ( <https://semopenalex.org/concept/C2776741419> ) 
    ( <https://semopenalex.org/concept/C2780662894> ) 
    ( <https://semopenalex.org/concept/C2780220085> ) 
    ( <https://semopenalex.org/concept/C2780347363> ) 
    ( <https://semopenalex.org/concept/C2776250893> ) 
    ( <https://semopenalex.org/concept/C2779714222> ) 
    ( <https://semopenalex.org/concept/C2777956544> ) 
    ( <https://semopenalex.org/concept/C2776122126> ) 
    ( <https://semopenalex.org/concept/C2777911022> ) 
    ( <https://semopenalex.org/concept/C2778620428> ) 
    ( <https://semopenalex.org/concept/C2780268429> ) 
    ( <https://semopenalex.org/concept/C2780479087> ) 
    ( <https://semopenalex.org/concept/C2781007269> ) 
    ( <https://semopenalex.org/concept/C107524782> ) 
    ( <https://semopenalex.org/concept/C107641696> ) 
    ( <https://semopenalex.org/concept/C2909484270> ) 
    ( <https://semopenalex.org/concept/C2992176824> ) 
    ( <https://semopenalex.org/concept/C2776418720> ) 
    ( <https://semopenalex.org/concept/C2908801736> ) 
    ( <https://semopenalex.org/concept/C2994599478> ) 
    ( <https://semopenalex.org/concept/C2779732806> ) 
    ( <https://semopenalex.org/concept/C2778583998> ) 
    ( <https://semopenalex.org/concept/C2779773560> ) 
    ( <https://semopenalex.org/concept/C2780333324> ) 
    ( <https://semopenalex.org/concept/C2776926547> ) 
    ( <https://semopenalex.org/concept/C2777575454> ) 
    ( <https://semopenalex.org/concept/C2778232189> ) 
    ( <https://semopenalex.org/concept/C2781116421> ) 
    ( <https://semopenalex.org/concept/C2775836813> ) 
    ( <https://semopenalex.org/concept/C2776473159> ) 
    ( <https://semopenalex.org/concept/C2776820357> ) 
    ( <https://semopenalex.org/concept/C2776986184> ) 
    ( <https://semopenalex.org/concept/C2777598532> ) 
    ( <https://semopenalex.org/concept/C2779613018> ) 
    ( <https://semopenalex.org/concept/C2780012436> ) 
    ( <https://semopenalex.org/concept/C2780938664> ) 
    ( <https://semopenalex.org/concept/C2780650970> ) 
    ( <https://semopenalex.org/concept/C518705261> ) 
    ( <https://semopenalex.org/concept/C2781460036> ) 
    ( <https://semopenalex.org/concept/C2776348250> ) 
    ( <https://semopenalex.org/concept/C2778692183> ) 
    ( <https://semopenalex.org/concept/C2778784962> ) 
    ( <https://semopenalex.org/concept/C2779959501> ) 
    ( <https://semopenalex.org/concept/C2780299902> ) 
    ( <https://semopenalex.org/concept/C2777001951> ) 
    ( <https://semopenalex.org/concept/C2778164554> ) 
    ( <https://semopenalex.org/concept/C2779333224> ) 
    ( <https://semopenalex.org/concept/C3060791> ) 
    ( <https://semopenalex.org/concept/C55034048> ) 
    ( <https://semopenalex.org/concept/C2777497123> ) 
    ( <https://semopenalex.org/concept/C2781423396> ) 
    ( <https://semopenalex.org/concept/C2779855799> ) 
    ( <https://semopenalex.org/concept/C2778370115> ) 
    ( <https://semopenalex.org/concept/C2778024200> ) 
    ( <https://semopenalex.org/concept/C2776943423> ) 
    ( <https://semopenalex.org/concept/C2778421575> ) 
    ( <https://semopenalex.org/concept/C2776643329> ) 
    ( <https://semopenalex.org/concept/C2776855439> ) 
    ( <https://semopenalex.org/concept/C2779209236> ) 
    ( <https://semopenalex.org/concept/C545314008> ) 
    ( <https://semopenalex.org/concept/C139275648> ) 
    ( <https://semopenalex.org/concept/C2777604165> ) 
    ( <https://semopenalex.org/concept/C2778218979> ) 
    ( <https://semopenalex.org/concept/C2779731873> ) 
    ( <https://semopenalex.org/concept/C2778964498> ) 
    ( <https://semopenalex.org/concept/C2780718027> ) 
    ( <https://semopenalex.org/concept/C2776082946> ) 
    ( <https://semopenalex.org/concept/C2777723521> ) 
    ( <https://semopenalex.org/concept/C2777099253> ) 
    ( <https://semopenalex.org/concept/C2780168142> ) 
    ( <https://semopenalex.org/concept/C2777971045> ) 
    ( <https://semopenalex.org/concept/C2780359839> ) 
    ( <https://semopenalex.org/concept/C2779965645> ) 
    ( <https://semopenalex.org/concept/C2780322005> ) 
    ( <https://semopenalex.org/concept/C2779895586> ) 
    ( <https://semopenalex.org/concept/C2777807078> ) 
    ( <https://semopenalex.org/concept/C2776354463> ) 
    ( <https://semopenalex.org/concept/C2779238441> ) 
    ( <https://semopenalex.org/concept/C2779923029> ) 
    ( <https://semopenalex.org/concept/C2779815167> ) 
    ( <https://semopenalex.org/concept/C2776818558> ) 
    ( <https://semopenalex.org/concept/C2780371428> ) 
    ( <https://semopenalex.org/concept/C2779774813> ) 
    ( <https://semopenalex.org/concept/C2780512574> ) 
    ( <https://semopenalex.org/concept/C2780771523> ) 
    ( <https://semopenalex.org/concept/C2776884468> ) 
    ( <https://semopenalex.org/concept/C2910449711> ) 
    ( <https://semopenalex.org/concept/C2780536345> ) 
    ( <https://semopenalex.org/concept/C2777264004> ) 
    ( <https://semopenalex.org/concept/C2777593132> ) 
    ( <https://semopenalex.org/concept/C2780231137> ) 
    ( <https://semopenalex.org/concept/C2779960720> ) 
    ( <https://semopenalex.org/concept/C2775956885> ) 
    ( <https://semopenalex.org/concept/C2778402161> ) 
    ( <https://semopenalex.org/concept/C2779991468> ) 
    ( <https://semopenalex.org/concept/C136203487> ) 
    ( <https://semopenalex.org/concept/C36388723> ) 
    ( <https://semopenalex.org/concept/C2780621315> ) 
    ( <https://semopenalex.org/concept/C2777765327> ) 
    ( <https://semopenalex.org/concept/C2780268226> ) 
    ( <https://semopenalex.org/concept/C2778672379> ) 
    ( <https://semopenalex.org/concept/C2779735895> ) 
    ( <https://semopenalex.org/concept/C2983497740> ) 
    ( <https://semopenalex.org/concept/C2780101333> ) 
    ( <https://semopenalex.org/concept/C2909675155> ) 
    ( <https://semopenalex.org/concept/C2777615863> ) 
    ( <https://semopenalex.org/concept/C2777399655> ) 
    ( <https://semopenalex.org/concept/C2780035688> ) 
    ( <https://semopenalex.org/concept/C2780197806> ) 
    ( <https://semopenalex.org/concept/C2777191950> ) 
    ( <https://semopenalex.org/concept/C2777507495> ) 
    ( <https://semopenalex.org/concept/C2779621457> ) 
    ( <https://semopenalex.org/concept/C2780833581> ) 
    ( <https://semopenalex.org/concept/C2776620988> ) 
    ( <https://semopenalex.org/concept/C2776716027> ) 
    ( <https://semopenalex.org/concept/C2778410449> ) 
    ( <https://semopenalex.org/concept/C2776981413> ) 
    ( <https://semopenalex.org/concept/C2777092883> ) 
    ( <https://semopenalex.org/concept/C2779851268> ) 
    ( <https://semopenalex.org/concept/C2780840399> ) 
    ( <https://semopenalex.org/concept/C3018498973> ) 
    ( <https://semopenalex.org/concept/C2779088137> ) 
    ( <https://semopenalex.org/concept/C2776700747> ) 
    ( <https://semopenalex.org/concept/C2777493842> ) 
    ( <https://semopenalex.org/concept/C2779937669> ) 
    ( <https://semopenalex.org/concept/C2910125355> ) 
    ( <https://semopenalex.org/concept/C2781236342> ) 
    ( <https://semopenalex.org/concept/C2776777027> ) 
    ( <https://semopenalex.org/concept/C2779078858> ) 
    ( <https://semopenalex.org/concept/C2779740085> ) 
    ( <https://semopenalex.org/concept/C2781304537> ) 
    ( <https://semopenalex.org/concept/C2781385326> ) 
    ( <https://semopenalex.org/concept/C122246415> ) 
    ( <https://semopenalex.org/concept/C2909772498> ) 
    ( <https://semopenalex.org/concept/C2779767645> ) 
    ( <https://semopenalex.org/concept/C2779920484> ) 
    ( <https://semopenalex.org/concept/C2777891700> ) 
    ( <https://semopenalex.org/concept/C2776907353> ) 
    ( <https://semopenalex.org/concept/C2778736619> ) 
    ( <https://semopenalex.org/concept/C2780797419> ) 
    ( <https://semopenalex.org/concept/C57322979> ) 
    ( <https://semopenalex.org/concept/C2781199646> ) 
    ( <https://semopenalex.org/concept/C2779223589> ) 
    ( <https://semopenalex.org/concept/C2777842045> ) 
    ( <https://semopenalex.org/concept/C2779100257> ) 
    ( <https://semopenalex.org/concept/C2779447285> ) 
    ( <https://semopenalex.org/concept/C2778231335> ) 
    ( <https://semopenalex.org/concept/C2775971261> ) 
    ( <https://semopenalex.org/concept/C2778260499> ) 
    ( <https://semopenalex.org/concept/C2779029879> ) 
    ( <https://semopenalex.org/concept/C2776010925> ) 
    ( <https://semopenalex.org/concept/C2778577996> ) 
    ( <https://semopenalex.org/concept/C2910561336> ) 
    ( <https://semopenalex.org/concept/C2780371755> ) 
    ( <https://semopenalex.org/concept/C2778259205> ) 
    ( <https://semopenalex.org/concept/C2775854910> ) 
    ( <https://semopenalex.org/concept/C2778670693> ) 
    ( <https://semopenalex.org/concept/C55450435> ) 
    ( <https://semopenalex.org/concept/C2776659949> ) 
    ( <https://semopenalex.org/concept/C3020436252> ) 
    ( <https://semopenalex.org/concept/C2779384463> ) 
    ( <https://semopenalex.org/concept/C2780663194> ) 
    ( <https://semopenalex.org/concept/C2776458125> ) 
    ( <https://semopenalex.org/concept/C2908742158> ) 
    ( <https://semopenalex.org/concept/C2909720742> ) 
    ( <https://semopenalex.org/concept/C2909221355> ) 
    ( <https://semopenalex.org/concept/C2909677699> ) 
    ( <https://semopenalex.org/concept/C2910162304> ) 
    ( <https://semopenalex.org/concept/C2910824017> ) 
    ( <https://semopenalex.org/concept/C2994310350> ) 
    ( <https://semopenalex.org/concept/C2911010140> ) 
    ( <https://semopenalex.org/concept/C3018369135> ) 
    ( <https://semopenalex.org/concept/C3019760618> ) 
    ( <https://semopenalex.org/concept/C2776261758> ) 
    ( <https://semopenalex.org/concept/C2779687288> ) 
    ( <https://semopenalex.org/concept/C2908923111> ) 
    ( <https://semopenalex.org/concept/C2909532979> ) 
    ( <https://semopenalex.org/concept/C2909621830> ) 
    ( <https://semopenalex.org/concept/C2910045404> ) 
    ( <https://semopenalex.org/concept/C2910207319> ) 
    ( <https://semopenalex.org/concept/C2910215949> ) 
    ( <https://semopenalex.org/concept/C2910975744> ) 
    ( <https://semopenalex.org/concept/C3020533434> ) 
    ( <https://semopenalex.org/concept/C2779503344> ) 
    ( <https://semopenalex.org/concept/C2992639061> ) 
    ( <https://semopenalex.org/concept/C144133560> ) 
    ( <https://semopenalex.org/concept/C2993284677> ) 
    ( <https://semopenalex.org/concept/C3019896124> ) 
    ( <https://semopenalex.org/concept/C118518473> ) 
    ( <https://semopenalex.org/concept/C2988907029> ) 
    ( <https://semopenalex.org/concept/C2991680293> ) 
    ( <https://semopenalex.org/concept/C2989409935> ) 
    ( <https://semopenalex.org/concept/C149229913> ) 
    ( <https://semopenalex.org/concept/C139366241> ) 
    ( <https://semopenalex.org/concept/C2910001868> ) 
    ( <https://semopenalex.org/concept/C3018669867> ) 
    ( <https://semopenalex.org/concept/C2777240086> ) 
    ( <https://semopenalex.org/concept/C2984843768> ) 
    ( <https://semopenalex.org/concept/C15752686> ) 
    ( <https://semopenalex.org/concept/C2780262536> ) 
    ( <https://semopenalex.org/concept/C2908606465> ) 
    ( <https://semopenalex.org/concept/C2910343542> ) 
    ( <https://semopenalex.org/concept/C2780600973> ) 
    ( <https://semopenalex.org/concept/C2909222840> ) 
    ( <https://semopenalex.org/concept/C2909938017> ) 
    ( <https://semopenalex.org/concept/C2993569511> ) 
    ( <https://semopenalex.org/concept/C3020803494> ) 
    ( <https://semopenalex.org/concept/C2909026353> ) 
    ( <https://semopenalex.org/concept/C2909048080> ) 
    ( <https://semopenalex.org/concept/C2910368159> ) 
    ( <https://semopenalex.org/concept/C2987634937> ) 
    ( <https://semopenalex.org/concept/C3019879152> ) 
    ( <https://semopenalex.org/concept/C2781348932> ) 
    ( <https://semopenalex.org/concept/C150875184> ) 
    ( <https://semopenalex.org/concept/C2779848721> ) 
    ( <https://semopenalex.org/concept/C143998085> ) 
    ( <https://semopenalex.org/concept/C2909065710> ) 
    ( <https://semopenalex.org/concept/C2909065710> ) 
    ( <https://semopenalex.org/concept/C2909065710> ) 
    ( <https://semopenalex.org/concept/C2909065710> ) 
    ( <https://semopenalex.org/concept/C2909065710> ) 
    ( <https://semopenalex.org/concept/C2909065710> ) 
    ( <https://semopenalex.org/concept/C2909065710> ) 
    ( <https://semopenalex.org/concept/C2909065710> ) 
    ( <https://semopenalex.org/concept/C2909065710> ) 
    ( <https://semopenalex.org/concept/C2909065710> ) 
    ( <https://semopenalex.org/concept/C2909065710> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2909597000> ) 
    ( <https://semopenalex.org/concept/C2984488660> ) 
    ( <https://semopenalex.org/concept/C2780011460> ) 
    ( <https://semopenalex.org/concept/C3018890749> ) 
    ( <https://semopenalex.org/concept/C2993525830> ) 
    ( <https://semopenalex.org/concept/C3017724717> ) 
    ( <https://semopenalex.org/concept/C3020782553> ) 
    ( <https://semopenalex.org/concept/C2984969020> ) 
    ( <https://semopenalex.org/concept/C2779455797> ) 
    ( <https://semopenalex.org/concept/C2779455797> ) 
    ( <https://semopenalex.org/concept/C2776269092> ) 
    ( <https://semopenalex.org/concept/C2984901469> ) 
    ( <https://semopenalex.org/concept/C2775907726> ) 
    ( <https://semopenalex.org/concept/C2908623805> ) 
    ( <https://semopenalex.org/concept/C2994423619> ) 
    ( <https://semopenalex.org/concept/C2909830472> ) 
    ( <https://semopenalex.org/concept/C3020109028> ) 
    ( <https://semopenalex.org/concept/C2909196371> ) 
    ( <https://semopenalex.org/concept/C2778334751> ) 
    ( <https://semopenalex.org/concept/C2910623885> ) 
    ( <https://semopenalex.org/concept/C2911181187> ) 
    ( <https://semopenalex.org/concept/C2992244235> ) 
    ( <https://semopenalex.org/concept/C2993940100> ) 
    ( <https://semopenalex.org/concept/C2991803051> ) 
    ( <https://semopenalex.org/concept/C2993839484> ) 
    ( <https://semopenalex.org/concept/C3019203764> ) 
    ( <https://semopenalex.org/concept/C3019203764> ) 
    ( <https://semopenalex.org/concept/C3019203764> ) 
    ( <https://semopenalex.org/concept/C56423290> ) 
    ( <https://semopenalex.org/concept/C2910384678> ) 
    ( <https://semopenalex.org/concept/C2910384678> ) 
    ( <https://semopenalex.org/concept/C2910384678> ) 
    ( <https://semopenalex.org/concept/C2776432867> ) 
    ( <https://semopenalex.org/concept/C2983491779> ) 
    ( <https://semopenalex.org/concept/C87621631> ) 
    ( <https://semopenalex.org/concept/C520752033> ) 
    ( <https://semopenalex.org/concept/C2776863835> ) 
    ( <https://semopenalex.org/concept/C2780824610> ) 
    ( <https://semopenalex.org/concept/C2777047556> ) 
    ( <https://semopenalex.org/concept/C2776417487> ) 
    ( <https://semopenalex.org/concept/C3018611479> ) 
    ( <https://semopenalex.org/concept/C88484716> ) 
    ( <https://semopenalex.org/concept/C2780688901> ) 
    ( <https://semopenalex.org/concept/C2984065012> ) 
    ( <https://semopenalex.org/concept/C2780733421> ) 
    ( <https://semopenalex.org/concept/C183211975> ) 
    ( <https://semopenalex.org/concept/C2780615356> ) 
    ( <https://semopenalex.org/concept/C2780142257> ) 
    ( <https://semopenalex.org/concept/C2776668819> ) 
    ( <https://semopenalex.org/concept/C180823521> ) 
    ( <https://semopenalex.org/concept/C2983637589> ) 
    ( <https://semopenalex.org/concept/C2778373026> ) 
    ( <https://semopenalex.org/concept/C2780271382> ) 
    ( <https://semopenalex.org/concept/C2780271382> ) 
    ( <https://semopenalex.org/concept/C56691978> ) 
    ( <https://semopenalex.org/concept/C2780472225> ) 
    ( <https://semopenalex.org/concept/C3018615303> ) 
    ( <https://semopenalex.org/concept/C123963621> ) 
    ( <https://semopenalex.org/concept/C2779029635> ) 
    ( <https://semopenalex.org/concept/C2779307984> ) 
    ( <https://semopenalex.org/concept/C67268981> ) 
    ( <https://semopenalex.org/concept/C2778514029> ) 
    ( <https://semopenalex.org/concept/C2909957015> ) 
    ( <https://semopenalex.org/concept/C2776834974> ) 
    ( <https://semopenalex.org/concept/C2780608534> ) 
    ( <https://semopenalex.org/concept/C2776716733> ) 
    ( <https://semopenalex.org/concept/C2779962280> ) 
    ( <https://semopenalex.org/concept/C25435620> ) 
    ( <https://semopenalex.org/concept/C24566897> ) 
    ( <https://semopenalex.org/concept/C2777103068> ) 
    ( <https://semopenalex.org/concept/C182107563> ) 
    ( <https://semopenalex.org/concept/C182107563> ) 
    ( <https://semopenalex.org/concept/C2983437453> ) 
    ( <https://semopenalex.org/concept/C3018006013> ) 
    ( <https://semopenalex.org/concept/C2993958944> ) 
    ( <https://semopenalex.org/concept/C2994142871> ) 
    ( <https://semopenalex.org/concept/C3020437955> ) 
    ( <https://semopenalex.org/concept/C2993864201> ) 
    ( <https://semopenalex.org/concept/C2911015141> ) 
    ( <https://semopenalex.org/concept/C2910218225> ) 
    ( <https://semopenalex.org/concept/C2993314993> ) 
  }

  # ?concept ccf:ccf_term ?term .
  # SERVICE <https://semopenalex.org/sparql>
  {
    ?publication sp:hasConcept ?concept .
    ?publication a <https://semopenalex.org/class/Work> .
    ?publication fabio:hasPubMedId ?pmid .
  }
}
